### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cclauss** [comment]
Use @cclauss instead of the more complicated [cclauss]: https://github.com/cclauss

**Comment by cclauss** [comment]
Never mind...  It does NOT work!

**Comment by tjferry14** [comment]
@cclauss Wanna help finish this baby up?

**Comment by cclauss** [comment]
It DOES work.

**Comment by tjferry14** [comment]
Just tried and it didn't work. Doesn't really matter does it?

**Pull request merged**
